### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by jlarmstrongiv** [gideo-llc/backblaze-b2-upload-any#1]
I am trying to use the library with TypeScript, but I receive this build error:

`Type error: Property 'uploadAny' does not exist on type 'BackBlazeB2'.`

Is there a way to solve this error or use uploadAny without extending the B2 prototype?

**Comment by cdhowie** [comment]
There's a few ways you could handle this.

---

The first would be to encourage the backblaze-b2 maintainer to [merge this functionality](https://github.com/yakovkhalinsky/backblaze-b2/issues/90).

---

You could extend the TypeScript interface and then assert that the client meets the new interface.  I don't know what TypeScript interface name is in the library you are using, but assuming it's `B2Client` then it would look something like this:

```
interface B2ClientWithUploadAny extends B2Client {
  uploadAny(options: any): Promise<any>;
}

const b2client = (new B2({ ...})) as B2ClientWithUploadAny;
```

Of course, you may want to change `any` in the interface to be strongly-typed.  This is just an example of the technique.

---

You could assert the object is `any` when invoking `uploadAny()`:

```
(b2client as any).uploadAny({ ... })
.then(...)
```

---

You could use the [unintrusive](https://github.com/gideo-llc/backblaze-b2-upload-any#unintrusive) path but skip installing `uploadAny` on the prototype, and apply it manually to a client object:

```
const uploadAny = require('@gideo-llc/backblaze-b2-upload-any');

// Set up your b2client object, then:

uploadAny.call(b2client, { ... })
.then(...);
```

---

Let me know if this answers your question.

**Comment by jlarmstrongiv** [comment]
Wow, what a succinct and fast reply!  I went with the last option using the `.call` method and everything worked perfectly.  Thank you for taking the time to answer my question.

**Comment by cdhowie** [comment]
Happy to help! Please let me know if you encounter any issues. We've been using 0.1.3 in production for months without issue, but I'm always glad to fix any bugs that others find.
